### ISSUE TITLE
link to other colors of same product on product page

### ISSUE THREAD

**Issue by gregjotau** [gregjotau/kashmina-testament#1]
1. On the product page, make a link to all other products of the same type, but different colors
2. Use the fact that the first part of the sku of the product type is equal. SKUs are on the format MODEL-color, use the first part, MODEL part to know which product to link together
3. The links should be images

Example webpage:
https://famme.no/products/fleek-lx1-shoes

![image](https://user-images.githubusercontent.com/13047497/202197721-5484da17-fa4b-4349-8a87-04496314ca22.png)

Note that the implementation on famme.no example is not possible on this store since it uses "color" option in shopify, thus have more variants per product in the backend. 

Example of website now: 

https://www.kashmina.no/collections/forside-collection-slideshow/products/kashmirgenser-hedda-toast-1

Proposed solution:

1. The skus already have a prefix for the same items, example 123-blue, 123-red
2. Use the sku to create a grouping for which variants to display as links on the options
3. Sold out products should not be linked (check inventory quantity)

**Comment by fairy-code-mother** [comment]
This PR has been released to the live theme.
